/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 5
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Control_Reg.h>
#include <SRCLK_aliases.h>
#include <SRCLK.h>
#include <Latch_aliases.h>
#include <Latch.h>
#include <OE_aliases.h>
#include <OE.h>
#include <SRCLR_aliases.h>
#include <SRCLR.h>
#include <SER_aliases.h>
#include <SER.h>
#include <SRCLK_Red_aliases.h>
#include <SRCLK_Red.h>
#include <Latch_Red_aliases.h>
#include <Latch_Red.h>
#include <SER_Red_aliases.h>
#include <SER_Red.h>
#include <Control_Reg_Red.h>
#include <SRCLK_Blue_aliases.h>
#include <SRCLK_Blue.h>
#include <Latch_Blue_aliases.h>
#include <Latch_Blue.h>
#include <SER_Blue_aliases.h>
#include <SER_Blue.h>
#include <Control_Reg_Blue.h>
#include <CapSense_CSD.h>
#include <CapSense_CSD_CSHL.h>
#include <CapSense_CSD_Pins.h>
#include <CapSense_CSD_TunerHelper.h>
#include <isr_sleep.h>
#include <SleepTimer.h>
#include <isr_flash.h>
#include <Timer.h>
#include <LCD.h>
#include <UART.h>
#include <Timer_Sent.h>
#include <isr_Sent.h>
#include <CapSense_CSD_CompCH0.h>
#include <CapSense_CSD_IdacCH0.h>
#include <CapSense_CSD_AMuxCH0.h>
#include <CapSense_CSD_IntClock.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <UART_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
